package com.tabat.hibernate.entities;
// Generated 17-Jan-2022 19:42:55 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Area generated by hbm2java
 */
@Entity
@Table(name="area"
    ,catalog="tabatapp"
)
public class Area  implements java.io.Serializable {


     private Integer id;
     private City city;
     private String nameAr;
     private String nameEn;
     private Set<ConsumerAddress> consumerAddresses = new HashSet<ConsumerAddress>(0);
     private Set<Order> orders = new HashSet<Order>(0);

    public Area() {
    }

	
    public Area(String nameAr, String nameEn) {
        this.nameAr = nameAr;
        this.nameEn = nameEn;
    }
    public Area(City city, String nameAr, String nameEn, Set<ConsumerAddress> consumerAddresses, Set<Order> orders) {
       this.city = city;
       this.nameAr = nameAr;
       this.nameEn = nameEn;
       this.consumerAddresses = consumerAddresses;
       this.orders = orders;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="city_id")
    public City getCity() {
        return this.city;
    }
    
    public void setCity(City city) {
        this.city = city;
    }

    
    @Column(name="name_ar", nullable=false)
    public String getNameAr() {
        return this.nameAr;
    }
    
    public void setNameAr(String nameAr) {
        this.nameAr = nameAr;
    }

    
    @Column(name="name_en", nullable=false)
    public String getNameEn() {
        return this.nameEn;
    }
    
    public void setNameEn(String nameEn) {
        this.nameEn = nameEn;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="area")
    public Set<ConsumerAddress> getConsumerAddresses() {
        return this.consumerAddresses;
    }
    
    public void setConsumerAddresses(Set<ConsumerAddress> consumerAddresses) {
        this.consumerAddresses = consumerAddresses;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="area")
    public Set<Order> getOrders() {
        return this.orders;
    }
    
    public void setOrders(Set<Order> orders) {
        this.orders = orders;
    }




}


