package com.tabat.hibernate.entities;
// Generated 17-Jan-2022 19:42:55 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * City generated by hbm2java
 */
@Entity
@Table(name="city"
    ,catalog="tabatapp"
    , uniqueConstraints = {@UniqueConstraint(columnNames="name_en"), @UniqueConstraint(columnNames="name_ar")} 
)
public class City  implements java.io.Serializable {


     private Integer id;
     private String nameAr;
     private String nameEn;
     private Set<Area> areas = new HashSet<Area>(0);

    public City() {
    }

	
    public City(String nameAr, String nameEn) {
        this.nameAr = nameAr;
        this.nameEn = nameEn;
    }
    public City(String nameAr, String nameEn, Set<Area> areas) {
       this.nameAr = nameAr;
       this.nameEn = nameEn;
       this.areas = areas;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    
    @Column(name="name_ar", unique=true, nullable=false, length=45)
    public String getNameAr() {
        return this.nameAr;
    }
    
    public void setNameAr(String nameAr) {
        this.nameAr = nameAr;
    }

    
    @Column(name="name_en", unique=true, nullable=false, length=45)
    public String getNameEn() {
        return this.nameEn;
    }
    
    public void setNameEn(String nameEn) {
        this.nameEn = nameEn;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="city")
    public Set<Area> getAreas() {
        return this.areas;
    }
    
    public void setAreas(Set<Area> areas) {
        this.areas = areas;
    }




}


