package com.tabat.hibernate.entities;
// Generated 17-Jan-2022 19:42:55 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Consumer generated by hbm2java
 */
@Entity
@Table(name="consumer"
    ,catalog="tabatapp"
    , uniqueConstraints = {@UniqueConstraint(columnNames="username"), @UniqueConstraint(columnNames="phone")} 
)
public class Consumer  implements java.io.Serializable {


     private Integer id;
     private String username;
     private String password;
     private String fullname;
     private String phone;
     private String gendre;
     private Set<ConsumerAddress> consumerAddresses = new HashSet<ConsumerAddress>(0);
     private Set<Order> orders = new HashSet<Order>(0);

    public Consumer() {
    }

	
    public Consumer(String username, String password, String fullname, String phone) {
        this.username = username;
        this.password = password;
        this.fullname = fullname;
        this.phone = phone;
    }
    public Consumer(String username, String password, String fullname, String phone, String gendre, Set<ConsumerAddress> consumerAddresses, Set<Order> orders) {
       this.username = username;
       this.password = password;
       this.fullname = fullname;
       this.phone = phone;
       this.gendre = gendre;
       this.consumerAddresses = consumerAddresses;
       this.orders = orders;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    
    @Column(name="username", unique=true, nullable=false, length=99)
    public String getUsername() {
        return this.username;
    }
    
    public void setUsername(String username) {
        this.username = username;
    }

    
    @Column(name="password", nullable=false)
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }

    
    @Column(name="fullname", nullable=false)
    public String getFullname() {
        return this.fullname;
    }
    
    public void setFullname(String fullname) {
        this.fullname = fullname;
    }

    
    @Column(name="phone", unique=true, nullable=false, length=25)
    public String getPhone() {
        return this.phone;
    }
    
    public void setPhone(String phone) {
        this.phone = phone;
    }

    
    @Column(name="gendre", length=45)
    public String getGendre() {
        return this.gendre;
    }
    
    public void setGendre(String gendre) {
        this.gendre = gendre;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="consumer")
    public Set<ConsumerAddress> getConsumerAddresses() {
        return this.consumerAddresses;
    }
    
    public void setConsumerAddresses(Set<ConsumerAddress> consumerAddresses) {
        this.consumerAddresses = consumerAddresses;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="consumer")
    public Set<Order> getOrders() {
        return this.orders;
    }
    
    public void setOrders(Set<Order> orders) {
        this.orders = orders;
    }




}


