package com.tabat.hibernate.entities;
// Generated 17-Jan-2022 19:42:55 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * ProviderUser generated by hbm2java
 */
@Entity
@Table(name="provider_user"
    ,catalog="tabatapp"
    , uniqueConstraints = @UniqueConstraint(columnNames="username") 
)
public class ProviderUser  implements java.io.Serializable {


     private Integer id;
     private Provider provider;
     private String username;
     private String password;
     private Byte active;
     private int branchId;

    public ProviderUser() {
    }

	
    public ProviderUser(Provider provider, String username, String password, int branchId) {
        this.provider = provider;
        this.username = username;
        this.password = password;
        this.branchId = branchId;
    }
    public ProviderUser(Provider provider, String username, String password, Byte active, int branchId) {
       this.provider = provider;
       this.username = username;
       this.password = password;
       this.active = active;
       this.branchId = branchId;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="provider_id", nullable=false)
    public Provider getProvider() {
        return this.provider;
    }
    
    public void setProvider(Provider provider) {
        this.provider = provider;
    }

    
    @Column(name="username", unique=true, nullable=false, length=100)
    public String getUsername() {
        return this.username;
    }
    
    public void setUsername(String username) {
        this.username = username;
    }

    
    @Column(name="password", nullable=false)
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }

    
    @Column(name="active")
    public Byte getActive() {
        return this.active;
    }
    
    public void setActive(Byte active) {
        this.active = active;
    }

    
    @Column(name="branch_id", nullable=false)
    public int getBranchId() {
        return this.branchId;
    }
    
    public void setBranchId(int branchId) {
        this.branchId = branchId;
    }




}


