package com.tabat.hibernate.entities;
// Generated 17-Jan-2022 19:42:55 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Provider generated by hbm2java
 */
@Entity
@Table(name="provider"
    ,catalog="tabatapp"
    , uniqueConstraints = {@UniqueConstraint(columnNames="name_ar"), @UniqueConstraint(columnNames="name_en")} 
)
public class Provider  implements java.io.Serializable {


     private Integer id;
     private String nameAr;
     private String nameEn;
     private String hotline;
     private String logoPatchAr;
     private String logoPathEn;
     private Set<Category> categories = new HashSet<Category>(0);
     private Set<ProviderUser> providerUsers = new HashSet<ProviderUser>(0);

    public Provider() {
    }

	
    public Provider(String nameAr, String nameEn) {
        this.nameAr = nameAr;
        this.nameEn = nameEn;
    }
    public Provider(String nameAr, String nameEn, String hotline, String logoPatchAr, String logoPathEn, Set<Category> categories, Set<ProviderUser> providerUsers) {
       this.nameAr = nameAr;
       this.nameEn = nameEn;
       this.hotline = hotline;
       this.logoPatchAr = logoPatchAr;
       this.logoPathEn = logoPathEn;
       this.categories = categories;
       this.providerUsers = providerUsers;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    
    @Column(name="name_ar", unique=true, nullable=false)
    public String getNameAr() {
        return this.nameAr;
    }
    
    public void setNameAr(String nameAr) {
        this.nameAr = nameAr;
    }

    
    @Column(name="name_en", unique=true, nullable=false)
    public String getNameEn() {
        return this.nameEn;
    }
    
    public void setNameEn(String nameEn) {
        this.nameEn = nameEn;
    }

    
    @Column(name="hotline", length=25)
    public String getHotline() {
        return this.hotline;
    }
    
    public void setHotline(String hotline) {
        this.hotline = hotline;
    }

    
    @Column(name="logo_patch_ar")
    public String getLogoPatchAr() {
        return this.logoPatchAr;
    }
    
    public void setLogoPatchAr(String logoPatchAr) {
        this.logoPatchAr = logoPatchAr;
    }

    
    @Column(name="logo_path_en")
    public String getLogoPathEn() {
        return this.logoPathEn;
    }
    
    public void setLogoPathEn(String logoPathEn) {
        this.logoPathEn = logoPathEn;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="provider")
    public Set<Category> getCategories() {
        return this.categories;
    }
    
    public void setCategories(Set<Category> categories) {
        this.categories = categories;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="provider")
    public Set<ProviderUser> getProviderUsers() {
        return this.providerUsers;
    }
    
    public void setProviderUsers(Set<ProviderUser> providerUsers) {
        this.providerUsers = providerUsers;
    }




}


